### ISSUE TITLE
`MenuInstaller` could not be found

### ISSUE THREAD

**Issue by qe201020335** [Goobwabber/MultiplayerAvatars#11]
I just tried to build this from source but it failed due to this error.
In line 7 of MultiplayerAvatars.HarmonyPatches.LobbyAvatarPatches.cs

```[HarmonyPatch(typeof(MenuInstaller), "InstallBindings", MethodType.Normal)]```

`MenuInstaller` cannot be found anywhere else in this project, is this from a missed import?

**Comment by whymoo** [comment]
Is this related https://github.com/ErisApps/SongRequestManager/blob/dcfad26be2bf3b363a24e1dd616f2e3a1d986dd4/SongRequestManager/Installers/MenuInstaller.cs

**Comment by whymoo** [comment]
> I just tried to build this from source but it failed due to this error.
> In line 7 of MultiplayerAvatars.HarmonyPatches.LobbyAvatarPatches.cs
> 
> `[HarmonyPatch(typeof(MenuInstaller), "InstallBindings", MethodType.Normal)]`
> 
> `MenuInstaller` cannot be found anywhere else in this project, is this from a missed import?
Is this related https://github.com/ErisApps/SongRequestManager/blob/dcfad26be2bf3b363a24e1dd616f2e3a1d986dd4/SongRequestManager/Installers/MenuInstaller.cs

**Comment by Goobwabber** [comment]
not related

**Comment by Goobwabber** [comment]
fixed in 9c6b978

**Comment by qe201020335** [comment]
Thanks
