### ISSUE TITLE
non-public avatars

### ISSUE THREAD

**Issue by koolcat200** [Goobwabber/MultiplayerAvatars#15]
Does this mod work for avatars that are not public?, or is this mod only for avatars that are on places like ModelSaber?

**Comment by LucaFox** [comment]
It will currently download a copy of any avatar your friend is wearing from modelsaber. 

It will also work with custom avatars, but only if both players already have a copy of the avatar in their own CustomAvatars folder.

**Comment by koolcat200** [comment]
So as long as i give it to them it should load?

**Comment by LucaFox** [comment]
And they put it in the right place, and have the same version of this and all dependent mods as you.
Then yes.
