### ISSUE TITLE
MultiplayerAvatars is depending on MultiplayerExtensions v0.4.3, but it says otherwise in readme

### ISSUE THREAD

**Issue by SteffoSpieler** [Goobwabber/MultiplayerAvatars#6]
As said in the title:
MultiplayerAvatars is depending on MultiplayerExtensions v0.4.3 (though the newest version is v0.4.5). In the README.md it says that v0.4.1 is required.

Maybe update the README.md and make MultiplayerAvatars depend on v0.4.5?

**Comment by LucaFox** [comment]
MPEX 0.4.3 is the stable version hosted on beatmods (i.e. available on ModAssistant). I'll update the reference when a new version is published there. 

If you'd like to use the latest, you can certainly clone/fork the repo and make a build locally, it should be as simple as updating the schema.json

I updated the readme to match though, thanks!
