### ISSUE TITLE
Beatsaber 1.13.5

### ISSUE THREAD

**Issue by Cyasi** [Goobwabber/MultiplayerAvatars#8]
Well it (https://github.com/Goobwabber/MultiplayerAvatars/issues/7) has been perfectly working for one day. Then the new Beatsaber Version released yesterday. 
The mods currently are a mess, but no stress. 

I have everything what is currently on Modassistant up to date + SiraUtil 2.5.2, CustomAvatars 5.2.1 and DynamicOpenVR 0.4.0 from github (cuz not on modassistant yet). Multiplayerextensions has no update since 13 days now (no suprise, beatsaber has made a lot of changes for multiplayer).

Couldn't test if the multiple downloads happen again. Will send more infos and the logs again if needed. (Otherwise we'll wait some days until at least multiplayerextension got their update and everything is in modassistant again.)

**Comment by schweinsbradl** [comment]
thx  for your work. i ll be waiting
